env:
  RUBY_VERSION: 2.7.5
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: eu-central-1
  SENDGRID_API_KEY: "Not Available"
  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}

name: Staging Deploy

on:
  push:
    branches:
      - staging-test

# Only allow 1 deploy at the same time
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency
concurrency: deploys

jobs:
  build:
    name: Build staging docker image

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout master
        with:
          ref: main
          token: ${{ secret.USER_TOKEN }}
 
      - name: Get branch name
        run: |
          git branch --show

      - name: Test step
        id: test_step
        run: |
          KEY_TAG=asd123
          echo "key_tag=${KEY_TAG}" >> $GITHUB_OUTPUT
      - name: Output test
        run: |
          echo ${{ steps.test_step.outputs.key_tag }} 
      - name: Get latest migration timestamp on master
        id: migration_timestamp
        run: |
          echo "MIGRATION_TIMESTAMP=$(find "db/migrate" | sort -nn | tail -n1 | cut -c 12-25)" >> $GITHUB_OUTPUT

      - name: Output timestamp
        run: |
          echo ${{ steps.migration_timestamp.outputs.MIGRATION_TIMESTAMP }} 

      - name: Checkout staging and rebase on master
        run: |
          git fetch
          git checkout --progress --force -B staging-test refs/remotes/origin/staging-test
          git branch --show
          git rebase main
          git push --force origin staging-test
      - name: Output environment variables
        run: |
          env

  # deploy:
  #   name: Deploy to staging
  #
  #   needs: build
  #
  #   steps:
